"""Initial migrations

Revision ID: 4e67f4f0f8c7
Revises: 
Create Date: 2021-06-04 18:28:35.939726+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e67f4f0f8c7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('administrators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_administrators_id'), 'administrators', ['id'], unique=False)
    op.create_index(op.f('ix_administrators_username'), 'administrators', ['username'], unique=True)
    op.create_table('cache_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cache_info_id'), 'cache_info', ['id'], unique=False)
    op.create_table('docker_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kernelVersion', sa.String(), nullable=True),
    sa.Column('operatingSystem', sa.String(), nullable=True),
    sa.Column('osVersion', sa.String(), nullable=True),
    sa.Column('osType', sa.String(), nullable=True),
    sa.Column('architecture', sa.String(), nullable=True),
    sa.Column('ncpu', sa.Integer(), nullable=True),
    sa.Column('memTotal', sa.Integer(), nullable=True),
    sa.Column('serverVersion', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_docker_info_id'), 'docker_info', ['id'], unique=False)
    op.create_table('os_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('distro', sa.String(), nullable=True),
    sa.Column('release', sa.String(), nullable=True),
    sa.Column('codename', sa.String(), nullable=True),
    sa.Column('kernel', sa.String(), nullable=True),
    sa.Column('arch', sa.String(), nullable=True),
    sa.Column('codepage', sa.String(), nullable=True),
    sa.Column('logofile', sa.String(), nullable=True),
    sa.Column('build', sa.String(), nullable=True),
    sa.Column('servicepack', sa.String(), nullable=True),
    sa.Column('uefi', sa.Boolean(), nullable=True),
    sa.Column('hypervisor', sa.Boolean(), nullable=True),
    sa.Column('remoteSession', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_os_info_id'), 'os_info', ['id'], unique=False)
    op.create_table('raspberry_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('processor', sa.String(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_raspberry_info_id'), 'raspberry_info', ['id'], unique=False)
    op.create_table('cpu_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('brand', sa.String(), nullable=True),
    sa.Column('vendor', sa.String(), nullable=True),
    sa.Column('family', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('stepping', sa.String(), nullable=True),
    sa.Column('revision', sa.String(), nullable=True),
    sa.Column('voltage', sa.String(), nullable=True),
    sa.Column('speed', sa.Float(), nullable=True),
    sa.Column('speedMin', sa.Float(), nullable=True),
    sa.Column('speedMax', sa.Float(), nullable=True),
    sa.Column('governor', sa.String(), nullable=True),
    sa.Column('cores', sa.Integer(), nullable=True),
    sa.Column('physicalCores', sa.Integer(), nullable=True),
    sa.Column('efficiencyCores', sa.Integer(), nullable=True),
    sa.Column('performanceCores', sa.Integer(), nullable=True),
    sa.Column('processors', sa.Integer(), nullable=True),
    sa.Column('socket', sa.String(), nullable=True),
    sa.Column('flags', sa.PickleType(), nullable=True),
    sa.Column('virtualization', sa.Boolean(), nullable=True),
    sa.Column('cache_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cache_id'], ['cache_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cpu_info_cache_id'), 'cpu_info', ['cache_id'], unique=False)
    op.create_index(op.f('ix_cpu_info_id'), 'cpu_info', ['id'], unique=False)
    op.create_table('system_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('version', sa.String(), nullable=True),
    sa.Column('sku', sa.String(), nullable=True),
    sa.Column('virtual', sa.Boolean(), nullable=True),
    sa.Column('virtualHost', sa.String(), nullable=True),
    sa.Column('raspberry_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['raspberry_id'], ['raspberry_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_info_id'), 'system_info', ['id'], unique=False)
    op.create_index(op.f('ix_system_info_raspberry_id'), 'system_info', ['raspberry_id'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('system_id', sa.Integer(), nullable=True),
    sa.Column('os_id', sa.Integer(), nullable=True),
    sa.Column('cpu_id', sa.Integer(), nullable=True),
    sa.Column('docker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cpu_id'], ['cpu_info.id'], ),
    sa.ForeignKeyConstraint(['docker_id'], ['docker_info.id'], ),
    sa.ForeignKeyConstraint(['os_id'], ['os_info.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['administrators.id'], ),
    sa.ForeignKeyConstraint(['system_id'], ['system_info.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_cpu_id'), 'clients', ['cpu_id'], unique=False)
    op.create_index(op.f('ix_clients_docker_id'), 'clients', ['docker_id'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_os_id'), 'clients', ['os_id'], unique=False)
    op.create_index(op.f('ix_clients_owner_id'), 'clients', ['owner_id'], unique=False)
    op.create_index(op.f('ix_clients_system_id'), 'clients', ['system_id'], unique=False)
    op.create_index(op.f('ix_clients_token'), 'clients', ['token'], unique=True)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('implementation', sa.String(), nullable=True),
    sa.Column('solution', sa.String(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('threads', sa.Integer(), nullable=True),
    sa.Column('tags', sa.PickleType(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_results_client_id'), 'results', ['client_id'], unique=False)
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_index(op.f('ix_results_client_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_clients_token'), table_name='clients')
    op.drop_index(op.f('ix_clients_system_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_owner_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_os_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_docker_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_cpu_id'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_system_info_raspberry_id'), table_name='system_info')
    op.drop_index(op.f('ix_system_info_id'), table_name='system_info')
    op.drop_table('system_info')
    op.drop_index(op.f('ix_cpu_info_id'), table_name='cpu_info')
    op.drop_index(op.f('ix_cpu_info_cache_id'), table_name='cpu_info')
    op.drop_table('cpu_info')
    op.drop_index(op.f('ix_raspberry_info_id'), table_name='raspberry_info')
    op.drop_table('raspberry_info')
    op.drop_index(op.f('ix_os_info_id'), table_name='os_info')
    op.drop_table('os_info')
    op.drop_index(op.f('ix_docker_info_id'), table_name='docker_info')
    op.drop_table('docker_info')
    op.drop_index(op.f('ix_cache_info_id'), table_name='cache_info')
    op.drop_table('cache_info')
    op.drop_index(op.f('ix_administrators_username'), table_name='administrators')
    op.drop_index(op.f('ix_administrators_id'), table_name='administrators')
    op.drop_table('administrators')
    # ### end Alembic commands ###
