"""Fix cache_info not being assembled correctly

Revision ID: a7625f5e83eb
Revises: 4e67f4f0f8c7
Create Date: 2021-06-04 19:56:15.835843+02:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7625f5e83eb'
down_revision = '4e67f4f0f8c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cache_info', sa.Column('l1d', sa.Integer(), nullable=True))
    op.add_column('cache_info', sa.Column('l1i', sa.Integer(), nullable=True))
    op.add_column('cache_info', sa.Column('l2', sa.Integer(), nullable=True))
    op.add_column('cache_info', sa.Column('l3', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cache_info', 'l3')
    op.drop_column('cache_info', 'l2')
    op.drop_column('cache_info', 'l1i')
    op.drop_column('cache_info', 'l1d')
    # ### end Alembic commands ###
